In [6]:
import numpy as np
import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5

# Flatten the images.
train_images = train_images.reshape((-1, 784))
test_images = test_images.reshape((-1, 784))

# Build the model.
model = Sequential([
  Dense(64, activation='relu', input_shape=(784,)),
  Dense(64, activation='relu'),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=5,
  batch_size=32,
)

# Evaluate the model.
model.evaluate(
  test_images,
  to_categorical(test_labels)
)

# Save the model to disk.
model.save_weights('model.h5')

# Load the model from disk later using:
# model.load_weights('model.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

2022-11-28 14:54:12.096877: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-28 14:54:50.330013: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3460 - accuracy: 0.8961
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1728 - accuracy: 0.9477
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1389 - accuracy: 0.9585
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1162 - accuracy: 0.9646
Epoch 5/5
1/1 [==============================] - 0s 76ms/step
[7 2 1 0 4]
[7 2 1 0 4]


In [7]:
import numpy as np
import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5

# Flatten the images.
train_images = train_images.reshape((-1, 784))
test_images = test_images.reshape((-1, 784))

# Build the model.
model = Sequential([
  Dense(64, activation='relu', input_shape=(784,)),
  Dense(64, activation='relu'),
  Dense(64, activation='relu'),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=10,
  batch_size=32,
)

# Evaluate the model.
model.evaluate(
  test_images,
  to_categorical(test_labels)
)

# Save the model to disk.
model.save_weights('model_better.h5')

# Load the model from disk later using:
# model.load_weights('model.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

Epoch 1/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3529 - accuracy: 0.8910
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1828 - accuracy: 0.9439
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1420 - accuracy: 0.9553
Epoch 4/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1210 - accuracy: 0.9612
Epoch 5/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1052 - accuracy: 0.9667
Epoch 6/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0999 - accuracy: 0.9677
Epoch 7/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0872 - accuracy: 0.9719
Epoch 8/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0827 - accuracy: 0.9732
Epoch 9/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0755 - accuracy: 0.9758
Epoch 10/10
1/1 [==============================] - 0s 51ms/step
[7 2 1 0 4]
[7 2 1

Увеличили точность с accuracy: 0.9568 до 0.9713 и сократили loss c 0.1393 до 0.0969 за счет добавления дополнительного слоя и увеличения количества эпох. 