In [31]:
import numpy as np

### Практическое задание №1

Все задания рекомендуется делать вручную, проверяя полученные результаты через NumPy.

__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    
__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

__5*.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

### Задание 1
а. Произведение не определено

б. Произведение определено, размерность 2х3

в. Произведение определено, размерность 8х8

г. Произведение определено, размерность 4х4

### Задание 2

In [32]:
A = np.array([[1, 2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

In [33]:
A + B

array([[5, 1],
       [3, 5]])

In [34]:
A.dot(B)

array([[ 4,  9],
       [12, -3]])

### Задание 3

In [35]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

### Задание 4

In [36]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A_T = A.T
A.dot(A_T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [37]:
A_T.dot(A).shape

(2, 2)

### Задание 5

In [39]:
def matrix_multiply(A,B):
    n = A.shape[0]
    m = A.shape[1]
    k = B.shape[0]
    s = B.shape[1]
    if m != k:
        print(f'Матрицы невозможно перемножить, так как количество строк 2-ой матрицы = {k} /nи' 
              'оно не совпадает с количеством столбцов 1-ой матрицы = {m}')
    else:
        Matrix = [[0 for x in range(s)] for y in range(n)] 
        for i in range(n):
            for j in range(s):
                w = 0
                while w < m:
                    Matrix[i][j] += A[i][w]*B[w][j]
                    w += 1
    return Matrix
B = A.T

In [40]:
for row in matrix_multiply(A,B):
    print(row)

[17, 18, 11]
[18, 29, 4]
[11, 4, 13]


### Практическое задание №2

Все задания рекомендуется выполнять вручную, проверяя полученные результаты с использованием NumPy.

__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

### Задание 1

a)

s
i
n
2
x
−
(
−
c
o
s
2
x
)
 = 1

In [41]:
B = np.matrix('4, 2, 3; 0, 5, 1; 0, 0, 9')
det(B)

NameError: name 'det' is not defined

In [42]:
C = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9')
det(C)

NameError: name 'det' is not defined

### Задание 2

а) 
d
e
t
(
A
2
)
 = 
d
e
t
(
A
)
×
d
e
t
(
A
)
 = 16

б) 
d
e
t
(
A
T
)
 = 
d
e
t
(
A
)
 = 4

в) 
d
e
t
(
2
A
)
 = 
2
r
a
n
k
(
A
)
×
d
e
t
(
A
)
 = 
2
r
a
n
k
(
A
)
×
4
 = 

### Задание 3

In [43]:
rank = np.linalg.matrix_rank
inv = np.linalg.inv

In [44]:
A = np.matrix('-2, 7, -3; 4, -14, 6; -3, 7, 13')
print(f'Ранг матрицы равен {rank(A)}')
try:
    print(f'Обратная матрица {inv(A)}')
except:
    print('Нет обратной матрицы')

Ранг матрицы равен 2
Нет обратной матрицы


### Задание 4

In [45]:
A = np.matrix('1, 2, 3; 1, 1, 1; 2, 3, 4')
rank(A)

2

In [46]:
B = np.matrix('0, 0, 2, 1; 0, 0, 2, 2; 0, 0, 4, 3; 2, 3, 5, 6')
rank(B)

3