1. Найдите посредством NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


2. Для матрицы из предыдущего задания найдите:

    а) евклидову норму;
    
    б) норму Фробениуса.

### №1 

In [1]:
import numpy as np
from numpy import linalg as LA
np.set_printoptions(precision=2, suppress=True)
A = np.array([[1, 2, 0],
              [0, 0, 5],
             [3, -4, 2],
             [1, 6, 5],
             [0, 1, 0]])
print(f'Матрица A:\n{A}')

U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
print(f'Матрица D:\n{D}')
print(f'Матрица U:\n{U}')
print(f'Матрица V:\n{V}')

print(np.dot(np.dot(U, D), V.T))

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]
Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]
[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


### №2

In [2]:
# Евклидова норма:
D[0,0]

8.824868854820442

In [3]:
# Норма Фробениуса:
np.linalg.norm(A)

11.045361017187261

In [4]:
np.linalg.norm(A, ord='fro')

11.045361017187261

In [5]:
frob_norm = 0
for i in range(np.linalg.matrix_rank(A)):
    frob_norm += s[i]**2
frob_norm = np.sqrt(frob_norm)
frob_norm

11.045361017187261