In [3]:
import numpy as np





__1.__ Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$


In [4]:
def is_eig(A):
    w, v = np.linalg.eig(A)
    print(f'Матрица A:\n{A}')
    print(f'Собственные значения:\n{w}')
    print(f'Собственные векторы:\n{v}')

In [5]:
A = np.array([[-1, -6], [2, 6]])
is_eig(A)

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]



__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей:

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Покажите, что __любой__ вектор считается для него собственным.


##### Ответ:
 
−1(1	0	0	1 )(x1x2 )=λ(x1x2 ).λ=−1

Справедливо для любого вектора


__3.__ Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установите, считается ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.



##### Ответ:


  	 
{1+1=1⋅λ	−1+3=1⋅λ ⇒{λ=2	λ=2.

Вектор x=(1,1) является собственным вектором линейного оператора, заданного матрицей A.

In [12]:
A = np.array([[1, 1], [-1, 3]])
is_eig(A)

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2.00000002 1.99999998]
Собственные векторы:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


**4.** Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установите, считается ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

##### Ответ:

(0	3	0	3	0	0	0	0	3 )(3	−3	−4 )=λ(3	−3	−4 ){−9=3⋅λ	9=−3⋅λ	−12=−4⋅λ ⇒{λ=−3	λ=−3	λ=3 .

Вектор x=(3,−3,−4)не является собственным вектором линейного оператора, заданного матрицей A.

In [14]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
is_eig(A)

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
